spring:
  datasource:
    url: jdbc:mysql://10.96.2.137:3306/gemini?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
    username: root
    password: wym123
    driver-class-name: com.mysql.cj.jdbc.Driver
    #配置druid
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    # 数据库索引，默认0
    database: 0
    # 服务器IP地址
    host: 10.96.2.137
    # 连接端口
    port: 6179
    # Redis服务器连接密码（默认为空）
    password: wym123
    timeout: 2000ms

