spring:
  profiles:
    active: dev
  datasource:
    dbcp2:
      initial-size: 1
      min-idle: 3
      pool-prepared-statements: true
    tomcat:
      # 初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jackson:
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  cache:
    type: redis
  #去掉大量的调试信息CONDITIONS EVALUATION DELTA

server:
  servlet:
    context-path: /gemini
  port: 8090
  tomcat:
    uri-encoding: utf-8
  connection-timeout: 5000
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#去掉大量的调试信息CONDITIONS EVALUATION REPORT
logging.level.org.springframework.boot.autoconfigure: ERROR